export const SET_LIST_PROJECT = "SET_LIST_PROJECT";
export const RESET_LIST_PROJECT = "RESET_LIST_PROJECT";
export const SET_LIST_SERVICE_CHARGE = "RESET_LIST_PROJECT";
export const SET_LIST_DELIVERY_MODE = "RESET_LIST_PROJECT";
export const SET_LIST_TRANSPORT_MODE = "RESET_LIST_PROJECT";


