export const SET_LIST_PROJECT = "SET_LIST_PROJECT";
export const RESET_LIST_PROJECT = "RESET_LIST_PROJECT";
export const SET_LIST_SERVICE_CHARGE = "SET_LIST_SERVICE_CHARGE";
export const SET_LIST_DELIVERY_MODE = "SET_LIST_DELIVERY_MODE";
export const SET_LIST_TRANSPORT_MODE = "SET_LIST_TRANSPORT_MODE";
export const SET_LIST_TRANSPORT_TYPE = "SET_LIST_TRANSPORT_TYPE";

